# Site settings
title: Trioloop
email: info@trioloop.com
url: https://www.trioloop.com
description: "Trioloop is a software house. We build great apps that users love."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Trioloop Limited

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/trioloop
  - title: facebook
    url: https://www.facebook.com/trioloop
  - title: linkedin
    url: http://www.linkedin.com/trioloop
  - title: bitbucket
    url: http://bitbucket.org/trioloop
  - title: github
    url: https://github.com/trioloop

# Build settings
markdown: kramdown
permalink: pretty
